version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shoesclimate
    ports:
      - "5432:5432"
    volumes:
      - restful-ecommerce-db:/var/lib/postgresql/data

  api:
    image: dbrandy/restful-ecommerce
    build: .
    command: npm run db:migrate && npm start
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/shoeslcimate

volumes:
  restful-ecommerce-db:
